// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gobrain-home/Emocjonalna.tsx": () => import("../components/mockups/gobrain-home/Emocjonalna.tsx"),
  "./components/mockups/gobrain-home/Gamifikacja.tsx": () => import("../components/mockups/gobrain-home/Gamifikacja.tsx"),
  "./components/mockups/gobrain-home/Minimalna.tsx": () => import("../components/mockups/gobrain-home/Minimalna.tsx"),
  "./components/mockups/gobrain-home/Naukowa.tsx": () => import("../components/mockups/gobrain-home/Naukowa.tsx")
};
